# Generated by Django 3.2 on 2022-01-12 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='Aдрес')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('surname', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=250, verbose_name='Телефон')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='foodcartapp.product', verbose_name='продукт')),
            ],
        ),
    ]
