# Generated by Django 3.2 on 2022-02-15 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20220215_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='colled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Звонок клиенту'),
        ),
        migrations.AddField(
            model_name='order',
            name='derivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Заказ доставлен'),
        ),
        migrations.AddField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Заказ создан'),
        ),
    ]
