# Generated by Django 3.2 on 2022-02-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20220215_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличкой'), ('card', 'Картой'), ('not_selected', 'Неизвестно')], db_index=True, default='not_selected', max_length=12, verbose_name='Способ оплаты'),
        ),
    ]
